#!/bin/bash
# Setup script for local Supabase development
# Generates secure keys and creates .env from template
set -e

echo "=== Setting up local Supabase ==="

# Check Docker is running (optional - only warn if not running)
DOCKER_RUNNING=true
if ! docker info > /dev/null 2>&1; then
  echo "WARNING: Docker is not running. You'll need to start Docker before running 'docker compose up'."
  echo "Environment files will still be generated."
  DOCKER_RUNNING=false
fi

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  read -p ".env already exists. Overwrite? (y/N): " confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    echo "Aborted."
    exit 0
  fi
  # Backup existing .env before overwriting
  cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
  echo "Backed up existing .env to $ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Check for Node.js (required for JWT generation)
if ! command -v node &> /dev/null; then
  echo "ERROR: Node.js is not installed. Please install Node.js to generate JWT tokens."
  exit 1
fi

# Check Node.js version (18+ required for base64url support)
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  echo "ERROR: Node.js 18+ required for base64url encoding. Current version: $(node -v)"
  exit 1
fi

# Check for OpenSSL (required for secret generation)
if ! command -v openssl &> /dev/null; then
  echo "ERROR: OpenSSL is not installed. Please install OpenSSL."
  exit 1
fi

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -base64 32)
SECRET_KEY_BASE=$(openssl rand -base64 48)
# Realtime encrypts tenant secrets with AES-128-ECB, which requires a key of
# EXACTLY 16 bytes. Do NOT reuse SECRET_KEY_BASE (64 bytes) here — it crashes
# realtime with {:badarg, "Bad key size"} during seeds.exs on every boot.
REALTIME_DB_ENC_KEY=$(openssl rand -hex 8)
PG_META_CRYPTO_KEY=$(openssl rand -base64 24)
DASHBOARD_PASSWORD=$(openssl rand -hex 8)

echo "Generated secrets successfully."

# Generate JWT tokens for anon and service_role keys
# Requires node.js
generate_jwt() {
  local role=$1
  node -e "
    const crypto = require('crypto');
    const secret = '$JWT_SECRET';
    const header = Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');
    const now = Math.floor(Date.now()/1000);
    const payload = Buffer.from(JSON.stringify({
      role:'$role', iss:'supabase', iat:now, exp:now+10*365*24*60*60
    })).toString('base64url');
    const sig = crypto.createHmac('sha256', secret)
      .update(header+'.'+payload).digest('base64url');
    console.log(header+'.'+payload+'.'+sig);
  "
}

ANON_KEY=$(generate_jwt "anon")
SERVICE_ROLE_KEY=$(generate_jwt "service_role")

# Write .env for Docker Compose
cat > "$ENV_FILE" << EOF
# Auto-generated by setup-local-supabase.sh
# Docker Compose environment variables

SITE_URL=http://localhost:5173
ADDITIONAL_REDIRECT_URLS=
API_EXTERNAL_URL=http://localhost:8000
SUPABASE_PUBLIC_URL=http://localhost:8000

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

SECRET_KEY_BASE=${SECRET_KEY_BASE}
REALTIME_DB_ENC_KEY=${REALTIME_DB_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}

DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

KONG_HTTP_PORT=8000

SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=localhost
SMTP_PORT=25
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=Supabase

MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify
EOF

# Create .env.local for Vite app (at repo root, one level up) with VITE_ prefix
cat > "../.env.local" << EOF
# Auto-generated by setup-local-supabase.sh
# Vite app environment variables (prefix with VITE_)

VITE_SUPABASE_URL=http://localhost:8000
VITE_SUPABASE_ANON_KEY=${ANON_KEY}
EOF

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Credentials (save these!):"
echo "  Supabase URL:       http://localhost:8000"
echo "  Dashboard:          http://localhost:3001"
echo "  Dashboard user:     supabase"
echo "  Dashboard password: ${DASHBOARD_PASSWORD}"
echo "  Anon Key:           ${ANON_KEY}"
echo "  Service Role Key:   ${SERVICE_ROLE_KEY}"
echo "  DB Password:        ${POSTGRES_PASSWORD}"
echo ""
echo "Files created:"
echo "  .env          - Docker Compose configuration (in supabase/)"
echo "  ../.env.local - Vite app configuration at repo root (auto-loaded)"
echo ""
echo "To start:    docker compose up -d   (run from supabase/)"
echo "To stop:     docker compose down"
echo "To reset:    docker compose down -v"
echo ""
echo "Your app (run from repo root) uses local Supabase via .env.local"
echo "To switch back to cloud, delete .env.local and use .env.local.example"
