-- ===========================================================================
-- Seed content (DATA ONLY — no DDL). Auto-generated from prod CSV exports.
-- ===========================================================================
-- Source: tmp/prod-export/{quizzes,quiz_questions,quiz_options}.csv
-- Generated by parsing the CSVs and emitting FK-ordered, escaped SQL.
-- Re-generate by re-running the node parser against updated CSVs.
--
-- SCOPE: general_settings (real values) + quizzes/quiz_questions/quiz_options.
-- Binary documents live in storage; uploaded by scripts/seed-local-content.sh.
--
-- ── Schema/seed separation ──────────────────────────────────────────────
-- This file contains ONLY INSERT/UPDATE/DELETE/TRUNCATE — no DDL. See
-- seed/README.md. Every block is guarded by to_regclass() so a missing/
-- renamed table logs a NOTICE and skips instead of crashing.
--
-- ── Idempotency ─────────────────────────────────────────────────────────
-- Re-runnable: upserts for settings, TRUNCATE...CASCADE for quizzes (FK order).
--
-- ── Ownership ───────────────────────────────────────────────────────────
-- All quizzes assigned to the LOCAL admin (created by 06-seed-users.sql):
--   a0000000-0000-4000-8000-000000000001  (admin@vngeo.local)
-- Prod created_by UUIDs are NOT imported (single-admin local-dev decision).
--
-- ── Prod data anomaly (fixed inline, flagged for prod) ──────────────────
-- Question 33333333-...-333333333302 ("How long is the typical tax exemption
-- period...") had quiz_id = 33333333-...-333333333303, which is itself a
-- QUESTION id ("priority investment sectors"), not a quiz. That FK target
-- does not exist, so the insert would fail. Corrected to quiz #3 (...333),
-- the only valid parent. Verify and fix in prod.
-- ===========================================================================
-- Note: created_by is inlined as the literal local admin UUID below (not a
-- psql :variable), so this file runs correctly under any psql invocation,
-- including non-interactive -f file mode from the seed-runner. ON_ERROR_STOP
-- is set by the runner via -v ON_ERROR_STOP=1.

BEGIN;

-- ===========================================================================
-- 1. general_settings — real values
-- ===========================================================================
-- Overrides the placeholder defaults inserted by init/01-general_settings.sql
-- with the real production values.
DO $$
BEGIN
  IF to_regclass('public.general_settings') IS NULL THEN
    RAISE NOTICE 'Skipping general_settings seed: table does not exist';
  ELSE
    INSERT INTO general_settings (key, value, description) VALUES
      ('map_drawing_video_url',
       'https://www.youtube.com/embed/hrUFFjGDPuI',
       'URL for the map drawing tutorial video'),
      ('feedback_form_url',
       'https://docs.google.com/forms/d/e/1FAIpQLSeVsSJ9TF16HYvhE5clUTuPXD9ZKo_pzsUyJRSks83oxlftUQ/viewform?usp=header',
       'URL for the feedback Google Form')
    ON CONFLICT (key) DO UPDATE SET
      value       = EXCLUDED.value,
      description = EXCLUDED.description,
      updated_at  = now();
    RAISE NOTICE 'Seeded general_settings (%) rows', (SELECT count(*) FROM general_settings);
  END IF;
END $$;

-- ===========================================================================
-- 2. quizzes + quiz_questions + quiz_options — prod data
-- ===========================================================================
-- TRUNCATE in FK order (children->parent) for a clean slate, then INSERT in
-- dependency order (parent->children). UUID PKs, so RESTART IDENTITY is a
-- no-op but harmless. created_by forced to 'a0000000-0000-4000-8000-000000000001' for RLS.
DO $$
BEGIN
  IF to_regclass('public.quizzes') IS NULL THEN
    RAISE NOTICE 'Skipping quiz seed: public.quizzes does not exist';
  ELSE
    TRUNCATE TABLE public.quiz_options  RESTART IDENTITY CASCADE;
    TRUNCATE TABLE public.quiz_questions RESTART IDENTITY CASCADE;
    TRUNCATE TABLE public.quizzes        RESTART IDENTITY CASCADE;

    -- Quizzes (5 rows; created_by -> local admin)
    INSERT INTO quizzes (id, title, description, difficulty, status, time_limit, created_at, updated_at, created_by) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Vietnam Economic Zones - Basic Knowledge', 'Test your understanding of the fundamental concepts of Vietnam''s economic zones and their role in national development.', 'easy', 'published', 15, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00', 'a0000000-0000-4000-8000-000000000001'),
  ('22222222-2222-2222-2222-222222222222', 'Industrial Parks and Export Processing Zones', 'Explore the characteristics and functions of Vietnam''s industrial parks and export processing zones.', 'medium', 'published', 20, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00', 'a0000000-0000-4000-8000-000000000001'),
  ('33333333-3333-3333-3333-333333333333', 'Investment and Business in Economic Zones', 'Advanced knowledge about investment procedures, regulations, and business operations in Vietnam''s economic zones.', 'hard', 'published', 25, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00', 'a0000000-0000-4000-8000-000000000001'),
  ('03fe0db3-094e-4136-b46e-a324043e7f2b', 'Bài kiểm tra 1', 'Mô tả cho bài kiểm tra 1', 'medium', 'published', NULL, '2025-10-16 14:55:26.215687+00', '2025-11-06 14:29:55.804344+00', 'a0000000-0000-4000-8000-000000000001'),
  ('d95b7152-4549-4abf-a308-ed945b497d09', 'Dong bang song Hong', 'Bài kiểm tra đồng bằng sông Hồng 1', 'easy', 'published', NULL, '2025-11-06 14:56:18.827884+00', '2025-11-08 05:46:52.881596+00', 'a0000000-0000-4000-8000-000000000001');

    -- Questions (25 rows; includes 1 prod typo fix -- see header)
    INSERT INTO quiz_questions (id, quiz_id, question, explanation, allow_multiple_answers, order_index, created_at, updated_at) VALUES
  ('11111111-1111-1111-1111-111111111101', '11111111-1111-1111-1111-111111111111', 'What is the primary purpose of establishing economic zones in Vietnam?', 'Economic zones are established to attract foreign investment, promote exports, and create employment opportunities while developing specific industries and technologies.', FALSE, 1, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('11111111-1111-1111-1111-111111111102', '11111111-1111-1111-1111-111111111111', 'Which of the following is one of the key economic zones in Southern Vietnam?', 'The Southern Key Economic Zone includes Ho Chi Minh City and surrounding provinces, forming Vietnam''s largest economic hub.', FALSE, 2, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('11111111-1111-1111-1111-111111111103', '11111111-1111-1111-1111-111111111111', 'What benefits do companies typically receive in Vietnam''s economic zones?', 'Companies in economic zones enjoy various incentives including tax breaks, simplified customs procedures, and better infrastructure to encourage investment and growth.', TRUE, 3, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('11111111-1111-1111-1111-111111111104', '11111111-1111-1111-1111-111111111111', 'Which year marked a significant milestone in Vietnam''s economic zone development policy?', '2006 was significant as it marked the implementation of comprehensive regulations for economic zones, accelerating their development nationwide.', FALSE, 4, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('11111111-1111-1111-1111-111111111105', '11111111-1111-1111-1111-111111111111', 'What role do coastal economic zones play in Vietnam''s economy?', 'Coastal economic zones leverage Vietnam''s strategic maritime location to facilitate international trade, develop shipping industries, and attract export-oriented manufacturing.', FALSE, 5, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222201', '22222222-2222-2222-2222-222222222222', 'What is the main difference between an Industrial Park (IP) and an Export Processing Zone (EPZ)?', 'EPZs are specifically designed for export-oriented production with special customs privileges, while IPs can serve both domestic and export markets with more flexible operations.', FALSE, 1, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222202', '22222222-2222-2222-2222-222222222222', 'Which sectors are commonly found in Vietnam''s industrial parks?', 'Vietnam''s industrial parks host diverse sectors including electronics, textiles, food processing, and automotive industries to create a balanced industrial ecosystem.', TRUE, 2, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222203', '22222222-2222-2222-2222-222222222222', 'What infrastructure requirements must industrial parks meet?', 'Industrial parks must provide comprehensive infrastructure including power, water, waste treatment, roads, and telecommunications to support industrial operations.', TRUE, 3, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222204', '22222222-2222-2222-2222-222222222222', 'Which province is known for having the highest concentration of industrial parks in Northern Vietnam?', 'Bac Ninh province has emerged as a major industrial hub in Northern Vietnam, hosting numerous industrial parks with significant foreign investment, particularly in electronics manufacturing.', FALSE, 4, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222205', '22222222-2222-2222-2222-222222222222', 'What environmental requirements must industrial parks comply with?', 'Industrial parks must implement comprehensive environmental protection measures including waste treatment systems, emissions control, and environmental impact assessments.', FALSE, 5, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('22222222-2222-2222-2222-222222222206', '22222222-2222-2222-2222-222222222222', 'What is the typical corporate income tax rate for enterprises in export processing zones?', 'Enterprises in EPZs typically enjoy preferential tax rates of 10% for 15 years, compared to the standard 20% rate, to encourage export-oriented production.', FALSE, 6, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333301', '33333333-3333-3333-3333-333333333333', 'What documents are typically required for foreign investors to establish a business in an economic zone?', 'Foreign investors must provide comprehensive documentation including investment certificates, business licenses, capital proof, and project proposals to ensure compliance with Vietnamese regulations.', TRUE, 1, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333302', '33333333-3333-3333-3333-333333333333', 'How long is the typical tax exemption period for priority sectors in economic zones?', 'Priority sectors such as high-tech, environmental protection, and R&D typically receive 4 years of tax exemption followed by 50% reduction for the next 9 years.', FALSE, 2, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333303', '33333333-3333-3333-3333-333333333333', 'Which of the following are considered priority investment sectors in Vietnam''s economic zones?', 'Vietnam prioritizes high-tech industries, renewable energy, supporting industries, and R&D to drive technological advancement and sustainable development.', TRUE, 3, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333304', '33333333-3333-3333-3333-333333333333', 'What is the minimum capital requirement for foreign-invested projects in most economic zones?', 'While requirements vary by sector and project type, many economic zones have minimum capital requirements around $2-5 million USD to ensure substantial investment and commitment.', FALSE, 4, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333305', '33333333-3333-3333-3333-333333333333', 'What are the key advantages of the "One-Stop Shop" mechanism in economic zones?', 'The One-Stop Shop mechanism streamlines administrative procedures by consolidating multiple government services in one location, significantly reducing processing time and bureaucratic complexity.', TRUE, 5, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333306', '33333333-3333-3333-3333-333333333333', 'Which international agreements does Vietnam participate in that benefit economic zone businesses?', 'Vietnam''s participation in CPTPP, EVFTA, and RCEP provides economic zone businesses with enhanced market access, reduced tariffs, and streamlined trade procedures across major markets.', TRUE, 6, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('33333333-3333-3333-3333-333333333307', '33333333-3333-3333-3333-333333333333', 'What is the maximum land lease term for industrial projects in economic zones?', 'Industrial projects can typically lease land for up to 50 years with possible extensions, providing long-term stability for major investments and infrastructure development.', FALSE, 7, '2025-10-05 05:59:39.51964+00', '2025-10-05 05:59:39.51964+00'),
  ('25766b59-317f-4997-8971-26aa3244857d', 'd95b7152-4549-4abf-a308-ed945b497d09', 'Cảng biển lớn nhất của vùng là:', 'Đáp án: B
Hải Phòng là nơi có nhiều cảng biển lớn, cửa nhỏ ra biển quan trọng của vùng đồng bằng sông Hồng', FALSE, 2, '2025-11-08 05:46:54.064936+00', '2025-11-08 05:46:54.064936+00'),
  ('2fd8b7a4-4331-4a0b-82b3-d5b0ccc92ee0', 'd95b7152-4549-4abf-a308-ed945b497d09', 'Đồng bằng sông Hồng có đặc điểm dân cư nổi bật là:', 'Đáp án C
Đồng bằng sông Hồng có mật độ dân số cao nhất nước ta', FALSE, 0, '2025-11-08 05:46:53.333383+00', '2025-11-08 05:46:53.333383+00'),
  ('c9a5d97c-7b46-4dd1-ae74-3f3ab87644cf', '03fe0db3-094e-4136-b46e-a324043e7f2b', 'Câu hỏi 1', 'Do A và C đúng', TRUE, 0, '2025-10-16 14:55:59.232241+00', '2025-11-06 14:29:56.030036+00'),
  ('43920a3e-3926-414e-8892-ee90656e5114', '03fe0db3-094e-4136-b46e-a324043e7f2b', 'Demo 2', NULL, FALSE, 1, '2025-11-06 14:29:34.70963+00', '2025-11-06 14:29:56.429687+00'),
  ('e8013429-d128-447c-8d6a-df2e69dcde6c', 'd95b7152-4549-4abf-a308-ed945b497d09', 'Loại hình sản xuất nông nghiệp truyền thống của vùng là:', 'Đáp án: C
Nghề truyền thống lâu đời dựa vào đất phù sa màu mỡ', FALSE, 3, '2025-11-08 05:46:54.368729+00', '2025-11-08 05:46:54.368729+00'),
  ('b8cf2f4e-dd97-44d1-96c4-a2f5f998fa8e', 'd95b7152-4549-4abf-a308-ed945b497d09', 'Trung tâm kinh tế, chính trị, văn hóa lớn nhất của vùng là:', 'Đáp án: B
Thủ đô Hà Nội là trung tâm văn hóa, chính trị lâu đời lớn nhất vùng', FALSE, 1, '2025-11-08 05:46:53.759218+00', '2025-11-08 05:46:53.759218+00'),
  ('a31db27b-9290-428a-a42e-8f0cd1bd0cc8', 'd95b7152-4549-4abf-a308-ed945b497d09', 'Nguồn lao động ở đồng bằng sông Hồng có đặt điểm:', 'Đáp án; C
Đồng bằng sông Hồng có lao động đông, học vấn và tay nghề cao hơn trung bình cả nước.', FALSE, 4, '2025-11-08 05:46:54.690775+00', '2025-11-08 05:46:54.690775+00');

    -- Options (99 rows)
    INSERT INTO quiz_options (id, question_id, text, is_correct, order_index, created_at) VALUES
  ('a1f9a55f-6e00-4c93-8768-56d6e44f2859', '11111111-1111-1111-1111-111111111101', 'To attract foreign investment and promote economic development', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('302572e4-a3f6-4a6d-aba3-7bf7bb6633e8', '11111111-1111-1111-1111-111111111101', 'To restrict foreign businesses from entering the market', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('49dd084d-b4ad-419a-8896-8fbef349cbb9', '11111111-1111-1111-1111-111111111101', 'To increase taxes on local businesses', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('01bfb6f9-19ad-491e-93ae-ec97b7ee554b', '11111111-1111-1111-1111-111111111101', 'To limit industrial development', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('02102ecb-bc29-44fc-ab99-f0484a14e750', '11111111-1111-1111-1111-111111111102', 'Southern Key Economic Zone (Ho Chi Minh City area)', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('e79bfee1-1b1c-4ae6-a185-99696a2d0e62', '11111111-1111-1111-1111-111111111102', 'Hanoi Capital Region', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('e3243fe9-4e9b-4707-bc44-e0adb3b1df73', '11111111-1111-1111-1111-111111111102', 'Central Highlands Economic Zone', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('f2ac4e2f-e61d-441d-b984-9cf231edbbe9', '11111111-1111-1111-1111-111111111102', 'Mekong River Delta Zone', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('053601a7-4a45-4d05-980f-3224c63eead7', '11111111-1111-1111-1111-111111111103', 'Tax incentives and exemptions', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('ce08eace-e710-44e2-ac97-96c3cd7d7b23', '11111111-1111-1111-1111-111111111103', 'Streamlined customs procedures', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('bb89cc75-b62b-4820-9934-479767957cfa', '11111111-1111-1111-1111-111111111103', 'Modern infrastructure facilities', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('bf040936-6ac1-4088-adf2-bc53d629f5fa', '11111111-1111-1111-1111-111111111103', 'Higher corporate tax rates', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('b8c418eb-9f7a-490a-b16b-d6b617c7edf8', '11111111-1111-1111-1111-111111111104', '2006', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('749ed8dc-bdf1-4879-bf51-c466577df54b', '11111111-1111-1111-1111-111111111104', '1995', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('e089baae-07ec-4c2b-8c02-a051eaf89eed', '11111111-1111-1111-1111-111111111104', '2010', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('adfb6713-0bbf-44f0-8984-f2a3968ca0e1', '11111111-1111-1111-1111-111111111104', '2015', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('33a45ab1-274c-4d92-a5e3-ea8d36fab71d', '11111111-1111-1111-1111-111111111105', 'Facilitating international trade and export-oriented industries', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('56e9e52b-4d41-4d96-8a1a-b643532b662e', '11111111-1111-1111-1111-111111111105', 'Focusing solely on agriculture development', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('c5837524-08c2-44a0-8fb3-cff873d3f429', '11111111-1111-1111-1111-111111111105', 'Restricting maritime activities', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('3b6ee083-a4ef-460f-99e4-7143a8ced37a', '11111111-1111-1111-1111-111111111105', 'Promoting only domestic trade', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('a53856b2-2736-483d-a106-864d8fd5d795', '22222222-2222-2222-2222-222222222201', 'EPZs focus on export production with customs privileges, IPs serve both markets', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('477988bc-edb7-4133-95c6-be47abacd2f3', '22222222-2222-2222-2222-222222222201', 'There is no difference between them', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('7de8c970-a6a3-438b-be1e-9d3777805743', '22222222-2222-2222-2222-222222222201', 'IPs are only for foreign companies, EPZs are for domestic companies', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('84549234-02b2-4bca-a2d8-c12f42eae95f', '22222222-2222-2222-2222-222222222201', 'EPZs are larger than IPs', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('3e94ac37-c923-4007-bba9-d18c2357a159', '22222222-2222-2222-2222-222222222202', 'Electronics and technology', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('689f3fe6-76e2-44f5-b2bc-044ba67fbe30', '22222222-2222-2222-2222-222222222202', 'Textiles and garments', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('d2cda43d-40dd-47c5-a0e1-f22868461932', '22222222-2222-2222-2222-222222222202', 'Food processing', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('66b88999-423c-4cad-ac80-f0fa9b2b0f26', '22222222-2222-2222-2222-222222222202', 'Space exploration', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('301c6bb6-52ee-42e7-bcdb-0fd60bcbd04f', '22222222-2222-2222-2222-222222222203', 'Reliable power supply', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('b8a4bbff-e5de-4f2b-a4b1-16de9960b52a', '22222222-2222-2222-2222-222222222203', 'Water and waste treatment systems', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('73bb66c8-d1d6-447e-873b-799dd91a5a3a', '22222222-2222-2222-2222-222222222203', 'Road and telecommunications infrastructure', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('e066ad9e-3d4b-4652-a09d-176a31f18b66', '22222222-2222-2222-2222-222222222203', 'Shopping malls and entertainment centers', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('fb9a3365-1ce7-4179-9393-0fc29a707179', '22222222-2222-2222-2222-222222222204', 'Bac Ninh', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('f13938d9-372f-423a-9069-160117bad402', '22222222-2222-2222-2222-222222222204', 'Hanoi', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('b9289a9d-3339-4c52-a255-0b22363514e3', '22222222-2222-2222-2222-222222222204', 'Hai Phong', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('d1dded4a-0b6b-47d7-8bcf-7cc30748d86c', '22222222-2222-2222-2222-222222222204', 'Quang Ninh', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('87fd44ac-d00c-4454-8753-bbffe55d4120', '22222222-2222-2222-2222-222222222205', 'Comprehensive environmental protection and waste treatment measures', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('d10d8256-f9f4-4d1c-b971-317c94211d10', '22222222-2222-2222-2222-222222222205', 'No environmental requirements', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('4e164502-b56c-481e-b180-d7c00bdf1f46', '22222222-2222-2222-2222-222222222205', 'Only air quality monitoring', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('32f5494f-85a7-490b-8bbf-992c27433ccc', '22222222-2222-2222-2222-222222222205', 'Environmental requirements are optional', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('65fcd839-dc00-4253-9b82-0de42290cd79', '22222222-2222-2222-2222-222222222206', '10% for 15 years', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('55f6938b-cb98-4587-a74e-1295996e7bb7', '22222222-2222-2222-2222-222222222206', '20% standard rate', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('e6f861bf-655b-46e8-a0e0-b0f0c528ec2e', '22222222-2222-2222-2222-222222222206', '5% for 10 years', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('0101fe10-fb1c-488e-9505-5b1f130a1888', '22222222-2222-2222-2222-222222222206', '15% for 20 years', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('10faca0a-7b80-4948-b03d-099a75a7cb6e', '33333333-3333-3333-3333-333333333301', 'Investment Registration Certificate', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('e02bb90f-ae12-4656-9580-4dad9014b797', '33333333-3333-3333-3333-333333333301', 'Business Registration Certificate', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('2544bed4-153a-4a23-9882-bfff80112e73', '33333333-3333-3333-3333-333333333301', 'Capital verification documents', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('540b6d28-e510-419c-83d6-eb015794a5bc', '33333333-3333-3333-3333-333333333301', 'Driver''s license', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('3109b2e4-7876-4a99-8809-914b2875f3fe', '33333333-3333-3333-3333-333333333302', '4 years exemption + 9 years 50% reduction', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('91ff13de-30c3-433c-94ad-df500b6dfde2', '33333333-3333-3333-3333-333333333302', '2 years exemption + 4 years 50% reduction', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('266feefa-c757-4784-b02d-ba5b4008a9e5', '33333333-3333-3333-3333-333333333303', '10 years full exemption', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('40f0a3c3-6970-4673-94af-3aab6f9e1913', '33333333-3333-3333-3333-333333333302', 'No tax exemption available', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('d55f86c6-da0e-43bb-af11-53a93665796b', '33333333-3333-3333-3333-333333333303', 'High-technology industries', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('b51894f6-b881-4e2c-9b35-bc249b0cecc4', '33333333-3333-3333-3333-333333333303', 'Renewable energy projects', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('a42305f9-f707-4fde-a767-e34e2add881e', '33333333-3333-3333-3333-333333333303', 'Supporting industries for manufacturing', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('b5a9e726-4e0b-402d-ae44-da380d34af1c', '33333333-3333-3333-3333-333333333303', 'Traditional handicrafts only', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('fc67e5df-7948-48c9-9107-563308483b20', '33333333-3333-3333-3333-333333333304', 'Varies, but often $2-5 million USD', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('0595d2bc-e3f4-4b5b-a91c-15c019e87ad9', '33333333-3333-3333-3333-333333333304', '$100,000 USD', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('c6c19621-b8e6-43f6-97a6-cfe97b26dd9b', '33333333-3333-3333-3333-333333333304', '$50 million USD', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('a0ab2b9b-454e-4d11-9a6d-f4d7f3b0c9d8', '33333333-3333-3333-3333-333333333304', 'No minimum requirement', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('4f165b73-de52-4f7f-853f-862a9bebf69a', '33333333-3333-3333-3333-333333333305', 'Centralized administrative services', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('800afe35-bae2-49c7-8ccc-a4e0fcdf6c8f', '33333333-3333-3333-3333-333333333305', 'Reduced processing time', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('c8a6a1d3-97fa-4cdd-9f6d-296ccf552736', '33333333-3333-3333-3333-333333333305', 'Simplified procedures', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('0d711b6b-4117-42dc-8f73-dd1a5e980abb', '33333333-3333-3333-3333-333333333305', 'Higher fees for faster service', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('e0bf8674-bae6-400b-8c3a-f8377c18f7a1', '33333333-3333-3333-3333-333333333306', 'CPTPP (Comprehensive and Progressive Agreement for Trans-Pacific Partnership)', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('fc6801ea-3e3b-433a-bb6b-78f8689fc10d', '33333333-3333-3333-3333-333333333306', 'EVFTA (EU-Vietnam Free Trade Agreement)', TRUE, 2, '2025-10-05 05:59:39.51964+00'),
  ('0b9dd678-9c58-4c9f-817d-848a706dd8bc', '33333333-3333-3333-3333-333333333306', 'RCEP (Regional Comprehensive Economic Partnership)', TRUE, 3, '2025-10-05 05:59:39.51964+00'),
  ('0cbc5bba-2668-4ac1-b038-f43981d4cd25', '33333333-3333-3333-3333-333333333306', 'Antarctic Treaty', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('d2492938-c861-49fe-a292-511ffb03cb17', '33333333-3333-3333-3333-333333333307', 'Up to 50 years with possible extension', TRUE, 1, '2025-10-05 05:59:39.51964+00'),
  ('17dcb919-584b-4468-8719-75fc865d4e7a', '33333333-3333-3333-3333-333333333307', '10 years maximum', FALSE, 2, '2025-10-05 05:59:39.51964+00'),
  ('0a52edb2-5c55-40d2-9759-97a38e6845d7', '33333333-3333-3333-3333-333333333307', '99 years', FALSE, 3, '2025-10-05 05:59:39.51964+00'),
  ('eb199499-59ac-4088-aa4a-e474dd353600', '33333333-3333-3333-3333-333333333307', '25 years fixed', FALSE, 4, '2025-10-05 05:59:39.51964+00'),
  ('0dbec4ad-64b0-4a7a-9ab6-a4f239cc1b54', 'c9a5d97c-7b46-4dd1-ae74-3f3ab87644cf', 'A', TRUE, 0, '2025-11-06 14:29:56.289699+00'),
  ('16d9129a-eabb-4821-86f2-4b8b8ce3ba98', 'c9a5d97c-7b46-4dd1-ae74-3f3ab87644cf', 'B', FALSE, 1, '2025-11-06 14:29:56.289699+00'),
  ('94c48c4b-b201-426b-85ca-931f492d07bb', 'c9a5d97c-7b46-4dd1-ae74-3f3ab87644cf', 'C', TRUE, 2, '2025-11-06 14:29:56.289699+00'),
  ('1f081891-b184-43b5-af49-1bfd8deb63b4', 'c9a5d97c-7b46-4dd1-ae74-3f3ab87644cf', 'D', FALSE, 3, '2025-11-06 14:29:56.289699+00'),
  ('03b6aa8c-8f20-4876-9c52-69af19982581', '43920a3e-3926-414e-8892-ee90656e5114', '1', FALSE, 0, '2025-11-06 14:29:56.696341+00'),
  ('970d1d1f-4b00-4ddd-a815-1fea90dff713', '43920a3e-3926-414e-8892-ee90656e5114', '2', FALSE, 1, '2025-11-06 14:29:56.696341+00'),
  ('bbeb3dda-916b-4e1e-ad17-d02a2bfd7541', '43920a3e-3926-414e-8892-ee90656e5114', '3', TRUE, 2, '2025-11-06 14:29:56.696341+00'),
  ('acc21a4e-383f-4657-b4ff-b877ba5de7fe', '2fd8b7a4-4331-4a0b-82b3-d5b0ccc92ee0', 'A. Dân cư thưa thớt', FALSE, 0, '2025-11-08 05:46:53.602776+00'),
  ('51e45ce1-02f6-4f99-a747-5639396c0680', '2fd8b7a4-4331-4a0b-82b3-d5b0ccc92ee0', 'B. Phân bố đều giữa các vùng', FALSE, 1, '2025-11-08 05:46:53.602776+00'),
  ('73e8df86-3d1b-4a65-aeee-95b186072aba', '2fd8b7a4-4331-4a0b-82b3-d5b0ccc92ee0', 'C. Mật độ dân số cao nhất nước ta', TRUE, 2, '2025-11-08 05:46:53.602776+00'),
  ('d8000581-f0a6-479c-90aa-ea93dfbb90db', '2fd8b7a4-4331-4a0b-82b3-d5b0ccc92ee0', 'D. Chủ yếu sinh sống bằng nghề thủy sản', FALSE, 3, '2025-11-08 05:46:53.602776+00'),
  ('afe46c9d-9f2f-4569-bbc7-8ea104b45107', 'b8cf2f4e-dd97-44d1-96c4-a2f5f998fa8e', 'A. Hải Phòng', FALSE, 0, '2025-11-08 05:46:53.911904+00'),
  ('c5599ded-c871-4931-931b-305731c4b3df', 'b8cf2f4e-dd97-44d1-96c4-a2f5f998fa8e', 'B. Hà Nội', TRUE, 1, '2025-11-08 05:46:53.911904+00'),
  ('ff056d6f-2620-420e-8b5e-53b89af0d480', 'b8cf2f4e-dd97-44d1-96c4-a2f5f998fa8e', 'C. Nam Định', FALSE, 2, '2025-11-08 05:46:53.911904+00'),
  ('d327b71d-5a4b-4a4d-9557-1d7c4b80f28f', 'b8cf2f4e-dd97-44d1-96c4-a2f5f998fa8e', 'D. Hưng Yên', FALSE, 3, '2025-11-08 05:46:53.911904+00'),
  ('9483a866-ff43-43cd-a320-6616db7f6984', '25766b59-317f-4997-8971-26aa3244857d', 'A. Đà Nẵng', FALSE, 0, '2025-11-08 05:46:54.217412+00'),
  ('8db26ee5-40ca-4a51-a77e-eece7126c3a8', '25766b59-317f-4997-8971-26aa3244857d', 'B. Hải Phòng', TRUE, 1, '2025-11-08 05:46:54.217412+00'),
  ('4019c047-75e1-411c-b30a-9bc284ca79d2', '25766b59-317f-4997-8971-26aa3244857d', 'C. Nha Trang', FALSE, 2, '2025-11-08 05:46:54.217412+00'),
  ('87208493-fbeb-4f78-827e-4a26217e31c6', '25766b59-317f-4997-8971-26aa3244857d', 'D. Cần Thơ', FALSE, 3, '2025-11-08 05:46:54.217412+00'),
  ('1c817857-93d9-4a34-80bc-5f50461b109a', 'e8013429-d128-447c-8d6a-df2e69dcde6c', 'A. Trồng cây công nghiệp', FALSE, 0, '2025-11-08 05:46:54.533845+00'),
  ('2a7242c3-0319-4e54-ae27-24011768f2ec', 'e8013429-d128-447c-8d6a-df2e69dcde6c', 'B. Trồng cây ăn quả ôn đới', FALSE, 1, '2025-11-08 05:46:54.533845+00'),
  ('49a01d34-7c5c-4e17-a325-100817347c2a', 'e8013429-d128-447c-8d6a-df2e69dcde6c', 'C. Trồng lúa nước và rau màu', TRUE, 2, '2025-11-08 05:46:54.533845+00'),
  ('ebff7897-e0b9-496c-8656-ecf32b2854f5', 'e8013429-d128-447c-8d6a-df2e69dcde6c', 'D. Chăn nuôi gia súc lớn', FALSE, 3, '2025-11-08 05:46:54.533845+00'),
  ('9d9745d6-b305-46ea-bcd8-06a5737d880b', 'a31db27b-9290-428a-a42e-8f0cd1bd0cc8', 'A. Thiếu và yếu', FALSE, 0, '2025-11-08 05:46:54.857377+00'),
  ('b4663644-c63d-485f-a4d8-421533e12926', 'a31db27b-9290-428a-a42e-8f0cd1bd0cc8', 'B. Tập trung chủ yếu ở nông nghiệp', FALSE, 1, '2025-11-08 05:46:54.857377+00'),
  ('a71f9bbb-1e9b-458c-9645-c6e1db75e9e7', 'a31db27b-9290-428a-a42e-8f0cd1bd0cc8', 'C. Dồi dào, có trình độ kỹ thuật cao', TRUE, 2, '2025-11-08 05:46:54.857377+00'),
  ('c8ed37bd-c95b-462c-9de5-fdb7d38322f0', 'a31db27b-9290-428a-a42e-8f0cd1bd0cc8', 'D. Không có tay nghề', FALSE, 3, '2025-11-08 05:46:54.857377+00');

    RAISE NOTICE 'Seeded quizzes=%, questions=%, options=%',
      (SELECT count(*) FROM quizzes), (SELECT count(*) FROM quiz_questions), (SELECT count(*) FROM quiz_options);
  END IF;
END $$;

COMMIT;
